apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/KingMicky/Rails-DevOps-with-Tekton.git
  username: .....
  password: .....
