apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: rails-k8s-app:local
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:password@postgres:5432/postgres
            - name: SECRET_KEY_BASE
              value: dummykey1234567890abcdef
            - name: RAILS_ENV
              value: production
